version: '3.8'

services:
  geidea-payment-api:
    build: .
    container_name: geidea-api-service
    ports:
      - "8000:8000" # Map host port 8000 to container port 80
    env_file:
      - .env # Load environment variables from .env file
    restart: always